version: "3.7"

networks:
  #(SWARM_NETWORK):
  name: #(SWARM_NETWORK)
  external: true
  driver: overlay

services:
  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:2.3
    labels:
      service: hyperledger-fabric
    environment:
      - CORE_PEER_ID=peer0.org2.example.com

      # The address that other peers in the organization use to connect
      # to this peer.
      - CORE_PEER_ADDRESS=peer0.org2.example.com:9054

      # This name must match the name of the organization in a channel
      # configuration file in order for this peer to join that channel
      # succesfully.
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9054
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9055
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/localMsp

      # Endpoint of the vm management system. This value should be set
      # correctly to succesfully install and run chaincodes.
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock

      # Starts chaincode containers on the same bridge network as this
      # peer.
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE= #(SWARM_NETWORK)

      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/tls-ca-cert.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT= #(IP2):9054
      - CORE_PEER_GOSSIP_BOOTSTRAP= #(IP2):9054
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME= #(DB_USER)
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD= #(DB_PASSWORD)
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run:/host/var/run
      - ../organizations/certs/org2.example.com/peers/peer0.org2.example.com:/etc/hyperledger/fabric
      - ../configtx:/etc/hyperledger/peercfg
    ports:
      - 9054:9054
      - 9055:9055
      - 9443:9443
    depends_on:
      - couchdb1
    networks:
      -  #(SWARM_NETWORK)

  couchdb1:
    container_name: couchdb1
    image: couchdb:3.1.1
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER= #(DB_USER)
      - COUCHDB_PASSWORD= #(DB_PASSWORD)
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE= #(SWARM_NETWORK)
    ports:
      - "5984:5984"
    networks:
      -  #(SWARM_NETWORK)
    # volumes:
    #   - ../organizations/certs/org2.example.com/peers/peer0.org2.example.com/couchdb:/opt/couchdb/data
